name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          working-directory: pokemon-backend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: pokemon-backend

      - name: Run Tests
        run: npm test
        working-directory: pokemon-backend
